version: 2

jobs:
  deploy:
    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - add_ssh_keys:
          fingerprints:
            - "b0:b0:20:93:55:c2:d3:a3:7f:14:d0:7f:5c:50:91:82"

      - run:
          name: Setup gcp account credentials
          command: echo $GCP_SERVICE_ACCOUNT_JSON | base64 -d > ~/.gcp_service_account.json

      - checkout:
          path: depper

      - run:
          name: Clone deployment project
          command: |
            echo "StrictHostKeyChecking no" >> ~/.ssh/config
            git clone git@github.com:tidelift/deploy

      - setup_remote_docker

      - run:
          name: Build image
          working_directory: depper
          command: ~/deploy/tl-deploy-circleci build_image

      - run:
          name: Upload image
          working_directory: depper
          command: ~/deploy/tl-deploy-circleci upload_image

      - run:
          name: Tag latest
          working_directory: depper
          command: ~/deploy/tl-deploy-circleci tag_latest

      - run:
          name: Deploy worker
          working_directory: depper
          command: ~/deploy/tl-deploy-circleci rollout libraries-depper

workflows:
  version: 2
  circleci_build:
    jobs:
      - deploy:
          context: prod-cluster-info

